/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class goldengate_common_digest_MD5 */

#ifndef _Included_goldengate_common_digest_MD5
#define _Included_goldengate_common_digest_MD5
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     goldengate_common_digest_MD5
 * Method:    TransformJni
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_goldengate_common_digest_MD5_TransformJni
  (JNIEnv *, jobject, jintArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
